SET PROJECT_NAME=current_sensing_single_ended_oscillator_compact
rmdir /S /Q %PROJECT_NAME%
mkdir %PROJECT_NAME%
copy %PROJECT_NAME%-F_Cu.gtl %PROJECT_NAME%\%PROJECT_NAME%.GTL
copy %PROJECT_NAME%-F_Mask.gts %PROJECT_NAME%\%PROJECT_NAME%.GTS
copy %PROJECT_NAME%-F_SilkS.gto %PROJECT_NAME%\%PROJECT_NAME%.GTO
copy %PROJECT_NAME%-B_Cu.gbl %PROJECT_NAME%\%PROJECT_NAME%.GBL
copy %PROJECT_NAME%-B_Mask.gbs %PROJECT_NAME%\%PROJECT_NAME%.GBS
copy %PROJECT_NAME%-B_SilkS.gbo %PROJECT_NAME%\%PROJECT_NAME%.GBO
copy %PROJECT_NAME%-PTH.drl %PROJECT_NAME%\%PROJECT_NAME%.TXT
copy %PROJECT_NAME%-Edge_Cuts.gm1 %PROJECT_NAME%\%PROJECT_NAME%.GML
"C:\Program Files\7-Zip\7zfm.exe" %PROJECT_NAME%&
