SET PROJECT_NAME=teensy41_display_controls
rmdir /S /Q %PROJECT_NAME%
mkdir %PROJECT_NAME%
copy %PROJECT_NAME%-F_Cu.gbr %PROJECT_NAME%\%PROJECT_NAME%.GTL
copy %PROJECT_NAME%-F_Mask.gbr %PROJECT_NAME%\%PROJECT_NAME%.GTS
copy %PROJECT_NAME%-F_SilkS.gbr %PROJECT_NAME%\%PROJECT_NAME%.GTO
copy %PROJECT_NAME%-B_Cu.gbr %PROJECT_NAME%\%PROJECT_NAME%.GBL
copy %PROJECT_NAME%-B_Mask.gbr %PROJECT_NAME%\%PROJECT_NAME%.GBS
copy %PROJECT_NAME%-B_SilkS.gbr %PROJECT_NAME%\%PROJECT_NAME%.GBO
copy %PROJECT_NAME%-PTH.drl %PROJECT_NAME%\%PROJECT_NAME%.TXT
copy %PROJECT_NAME%-Edge_Cuts.gbr %PROJECT_NAME%\%PROJECT_NAME%.GML
"C:\Program Files\7-Zip\7zfm.exe" %PROJECT_NAME%&
