SET PROJECT_NAME=analog_switch_heterodyne
rmdir /S /Q %PROJECT_NAME%
mkdir %PROJECT_NAME%
copy %PROJECT_NAME%-F.Cu.gtl %PROJECT_NAME%\%PROJECT_NAME%.GTL
copy %PROJECT_NAME%-F.Mask.gts %PROJECT_NAME%\%PROJECT_NAME%.GTS
copy %PROJECT_NAME%-F.SilkS.gto %PROJECT_NAME%\%PROJECT_NAME%.GTO
copy %PROJECT_NAME%-B.Cu.gbl %PROJECT_NAME%\%PROJECT_NAME%.GBL
copy %PROJECT_NAME%-B.Mask.gbs %PROJECT_NAME%\%PROJECT_NAME%.GBS
copy %PROJECT_NAME%-B.SilkS.gbo %PROJECT_NAME%\%PROJECT_NAME%.GBO
copy %PROJECT_NAME%.drl %PROJECT_NAME%\%PROJECT_NAME%.TXT
copy %PROJECT_NAME%-Edge.Cuts.gm1 %PROJECT_NAME%\%PROJECT_NAME%.GML
"C:\Program Files\7-Zip\7zfm.exe" %PROJECT_NAME%&
